site_name: Best HTTP/2 Documentation
site_author: Tivadar Gy√∂rgy Nagy
site_url: http://u3d.as/5sb

theme: 
    name: windmill
#    custom_dir: 'theme/'
    search_index_only: true
    include_search_page: true

markdown_extensions:
 - admonition